#!/bin/sh
# Fix LAN bridge ports for BPI-R4 Pro 8X (MxL862xx DSA)
uci del network.@device[0].ports
uci add_list network.@device[0].ports='mxl_lan0'
uci add_list network.@device[0].ports='mxl_lan1'
uci add_list network.@device[0].ports='mxl_lan2'
uci add_list network.@device[0].ports='mxl_lan3'
uci add_list network.@device[0].ports='mxl_lan5'

# WAN on eth1 (Aeonsemi AS21xxx COMBO port)
uci set network.wan.device='eth1'
uci set network.wan6.device='eth1'

uci commit network
